[colors.primary]
background = "#1c1c1c"
foreground = "#E4E4E4"

[colors.normal]
black   = "#181818"
red     = "#F43841"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#9E95C7"
cyan    = "#95A99F"
white   = "#E4E4E4"

[colors.bright]
black   = "#52494E"
red     = "#FF4F58"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#AFAFD7"
cyan    = "#95A99F"
white   = "#F5F5F5"

[font]
normal = { family = "IosevkaTermNerdFont" }
bold = { family = "IosevkaTermNerdFont" }
italic = { family = "IosevkaTermNerdFont" }
bold_italic = { family = "IosevkaTermNerdFont" }
size = 16.0
offset = { x = 1, y = -1 }
